apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job
spec:
  completions: 5
  template:
    metadata:
      labels:
        app: batch-job
        version: v1 
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
    